updates to PPDM chapter
rbms-bsc/DCRMR pull request #122
Opened 2020-10-01 21:35 UTC by ladylazarus3

Hi @elizhobart,  here are the updates to the PPDM chapter that brings the manufacturer instructions into alignment with the publisher and distributor instructions.

i also did a line by line comparison for all instructions over the various types of PPDM elements (Parallel name of X, Name of X, Date of X, etc.) and made everything a bit smoother.  Understandably, over the course of the last few months the text had shifted around a bit.  PPDM was always a bit of a guinea pig chapter as far as text transfer and Github development went, so it was good to have a second look through everything.

kalan

2020-10-02 17:46 UTC, elizhobart commented on _pages/PPDM/Note-on-manufacture-statement.md
> +<a name="4.226.4.2">4.226.4.2</a> Make an explanatory note if the [Place of manufacture](/DCRMR/ppdm/Place-of-manufacture/) appearing on the manifestation is known to be fictitious or incorrect (see
Should be "Make a note on manufacture statement giving the basis for the correction if the ..." (continue from [Place of manufacture] unchanged) to mirror instructions at 4.206.4.2.

2020-10-05 17:55 UTC, elizhobart requested changes

2020-10-05 17:55 UTC, elizhobart commented on _pages/Ppdm/Parallel-place-of-manufacture.md
> +<a name="4.222.3.2">4.222.3.2</a> Transcribe remaining [Places of manufacture](/DCRMR/ppdm/Place-of-manufacture/) as parallel places of manufacture. If a parallel place of manufacture is from a diffe
Transcribe remaining Places of Publication" not hyperlinked in Parallel place of publication. This should be consistent.

2020-10-06 17:41 UTC, ladylazarus3 commented on _pages/PPDM/Name-of-publisher.md
updated language to match parallel name of distributor and parallel name of manufacturer

2020-10-06 17:41 UTC, ladylazarus3 commented on _pages/PPDM/Name-of-publisher.md
> +<a name="4.203.96.1">4.203.96.1</a> If the name of the distributor does not appear in the [Publisher statement](/DCRMR/ppdm/Publisher-statement/), and the name of the publisher has already been trans
fixed.  Thanks!

2020-10-06 17:41 UTC, ladylazarus3 commented on _pages/PPDM/Name-of-publisher.md
fixed!  Thanks! :)

2020-10-06 17:41 UTC, ladylazarus3 commented on _pages/PPDM/Name-of-publisher.md
> +<a name="4.203.5.1">4.203.5.1</a> If only the address, sign, or initials of the distributor, appears in lieu of the name, transcribe the statement containing the address, sign, or initials as the nam
fixed!  Thanks!

2020-10-06 17:41 UTC, ladylazarus3 commented on _pages/PPDM/Name-of-publisher.md
fixed!  Thanks!

2020-10-06 17:41 UTC, ladylazarus3 commented on _pages/PPDM/Name-of-distributor.md
> +<a name="4.213.6.2">4.213.6.2</a> **Alternative rule**. If the name as transcribed is known to be fictitious, transcribe it as it appears and supply in square brackets the actual name, if known. Give
thanks!  fixed.

2020-10-06 17:41 UTC, ladylazarus3 commented on _pages/PPDM/Date-of-publication.md
> +<a name="4.205.4.5">4.205.4.5</a> *Optionally,* substitute for it a formalized statement in square brackets. If the supplied date includes a day/month, use the sequence: day, month, year. Make a [Not
brought three elements into alignment for this instruction.

2020-10-06 17:42 UTC, merged